<?php

namespace Database\Seeders\Admin;

use App\Models\City;
use App\Models\State;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            'Abia' => [
                'Aba',
                'Umuahia',
                'Ohafia',
                'Arochukwu',
                'Bende',
                'Isiala Ngwa',
                'Osisioma',
                'Ikwuano',
                'Ukwa',
                'Obingwa',
            ],
            'Adamawa' => [
                'Yola',
                'Jimeta',
                'Mubi',
                'Numan',
                'Ganye',
                'Michika',
                'Gombi',
                'Hong',
                'Mayo-Belwa',
                'Fufore',
            ],
            'Akwa Ibom' => [
                'Uyo',
                'Eket',
                'Ikot Ekpene',
                'Oron',
                'Ikot Abasi',
                'Abak',
                'Etinan',
                'Ibeno',
                'Onna',
                'Itu',
                'Ibiono Ibom',
            ],
            'Anambra' => [
                'Onitsha',
                'Awka',
                'Nnewi',
                'Ekwulobia',
                'Ihiala',
                'Ogidi',
                'Nkpor',
                'Obosi',
                'Otuocha',
                'Atani',
                'Agulu',
                'Umunze',
                'Nanka',
            ],
            'Bauchi' => [
                'Bauchi',
                'Azare',
                'Misau',
                'Jama’are',
                'Ningi',
                'Dass',
                'Darazo',
                'Katagum',
                'Toro',
                'Giade',
            ],
            'Bayelsa' => [
                'Yenagoa',
                'Brass',
                'Nembe',
                'Sagbama',
                'Ekeremor',
                'Ogbia',
                'Kaiama',
            ],
            'Benue' => [
                'Makurdi',
                'Gboko',
                'Otukpo',
                'Katsina-Ala',
                'Adikpo',
                'Aliade',
                'Vandeikya',
                'Zaki-Biam',
            ],
            'Borno' => [
                'Maiduguri',
                'Biu',
                'Bama',
                'Dikwa',
                'Monguno',
                'Konduga',
                'Damboa',
                'Gubio',
                'Ngala',
            ],
            'Cross River' => [
                'Calabar',
                'Ikom',
                'Ogoja',
                'Ugep',
                'Obudu',
                'Akamkpa',
                'Obubra',
                'Odukpani',
                'Yakurr',
            ],
            'Delta' => [
                'Warri',
                'Effurun',
                'Asaba',
                'Sapele',
                'Ughelli',
                'Agbor',
                'Oghara',
                'Ozoro',
                'Koko',
                'Udu',
                'Abraka',
                'Ogwashi-Uku',
            ],
            'Ebonyi' => [
                'Abakaliki',
                'Afikpo',
                'Onueke',
                'Nkalagu',
                'Ohaukwu',
                'Ishielu',
                'Izzi',
                'Ezza',
                'Edda',
            ],
            'Edo' => [
                'Benin City',
                'Auchi',
                'Ekpoma',
                'Irrua',
                'Uromi',
                'Igarra',
                'Afuze',
                'Sabongida-Ora',
                'Fugar',
            ],
            'Ekiti' => [
                'Ado-Ekiti',
                'Ikere',
                'Ikole',
                'Ijero',
                'Ilawe',
                'Oye',
                'Aramoko',
                'Emure',
                'Ise',
                'Otun',
            ],
            'Enugu' => [
                'Enugu',
                'Nsukka',
                'Oji River',
                'Agbani',
                'Awgu',
                'Udi',
                '9th Mile',
                'Emene',
                'Abakpa',
                'New Haven',
            ],
            'Gombe' => [
                'Gombe',
                'Kaltungo',
                'Billiri',
                'Bajoga',
                'Dukku',
                'Deba',
                'Nafada',
            ],
            'Imo' => [
                'Owerri',
                'Orlu',
                'Okigwe',
                'Mbaise',
                'Oguta',
                'Ideato',
                'Nkwerre',
                'Ehime Mbano',
                'Obowo',
                'Ohaji',
            ],
            'Jigawa' => [
                'Dutse',
                'Hadejia',
                'Gumel',
                'Birnin Kudu',
                'Kazaure',
                'Ringim',
                'Garki',
                'Malam Madori',
                'Babura',
            ],
            'Kaduna' => [
                'Kaduna',
                'Zaria',
                'Kafanchan',
                'Kagoro',
                'Kachia',
                'Saminaka',
                'Birnin Gwari',
                'Kajuru',
                'Sabon Tasha',
                'Kawo',
            ],
            'Kano' => [
                'Kano',
                'Fagge',
                'Nassarawa',
                'Tarauni',
                'Dala',
                'Gwale',
                'Kumbotso',
                'Ungogo',
                'Wudil',
                'Bichi',
                'Gwarzo',
                'Rano',
            ],
            'Katsina' => [
                'Katsina',
                'Funtua',
                'Daura',
                'Dutsin-Ma',
                'Malumfashi',
                'Kankara',
                'Mani',
                'Bakori',
                'Jibia',
            ],
            'Kebbi' => [
                'Birnin Kebbi',
                'Argungu',
                'Yauri',
                'Zuru',
                'Jega',
                'Koko',
                'Bunza',
                'Dakingari',
            ],
            'Kogi' => [
                'Lokoja',
                'Okene',
                'Idah',
                'Anyigba',
                'Kabba',
                'Ajaokuta',
                'Ankpa',
                'Dekina',
                'Ejule',
            ],
            'Kwara' => [
                'Ilorin',
                'Offa',
                'Jebba',
                'Lafiagi',
                'Patigi',
                'Omu-Aran',
                'Kaiama',
                'Erin-Ile',
            ],
            'Lagos' => [
                'Ikeja',
                'Lagos Island',
                'Victoria Island',
                'Ikoyi',
                'Lekki',
                'Ajah',
                'Yaba',
                'Surulere',
                'Mushin',
                'Maryland',
                'Anthony',
                'Ojota',
                'Gbagada',
                'Ketu',
                'Magodo',
                'Ogba',
                'Agege',
                'Oshodi',
                'Ilupeju',
                'Fadeyi',
                'Palmgrove',
                'Alimosho',
                'Egbeda',
                'Akowonjo',
                'Ipaja',
                'Ayobo',
                'Iyana-Ipaja',
                'Abule-Egba',
                'Meiran',
                'Alagbado',
                'Dopemu',
                'Ikorodu',
                'Igbogbo',
                'Imota',
                'Epe',
                'Badagry',
                'Ojo',
                'Alaba',
                'Festac',
                'Amuwo-Odofin',
                'Satellite Town',
                'Trade Fair',
                'Mile 2',
                'Sangotedo',
                'Osapa',
                'Chevron',
                'Oniru',
                'Falomo',
                'Obalende',
            ],
            'Nasarawa' => [
                'Lafia',
                'Keffi',
                'Akwanga',
                'Karu',
                'Mararaba',
                'Masaka',
                'New Nyanya',
                'Nasarawa',
                'Doma',
                'Keana',
            ],
            'Niger' => [
                'Minna',
                'Suleja',
                'Bida',
                'Kontagora',
                'Mokwa',
                'Paikoro',
                'Borgu',
                'Lapai',
                'Shiroro',
            ],
            'Ogun' => [
                'Abeokuta',
                'Ota',
                'Sango',
                'Ifo',
                'Agbado',
                'Ijoko',
                'Atan',
                'Sagamu',
                'Iperu',
                'Ilisan',
                'Simawa',
                'Ijebu-Ode',
                'Ikenne',
                'Ilaro',
                'Ijebu-Igbo',
                'Oru',
                'Ago-Iwoye',
                'Odogbolu',
            ],
            'Ondo' => [
                'Akure',
                'Ondo City',
                'Owo',
                'Ikare',
                'Ore',
                'Akungba',
                'Idanre',
                'Ile-Oluji',
                'Okitipupa',
                'Ilaje',
            ],
            'Osun' => [
                'Osogbo',
                'Ile-Ife',
                'Ilesa',
                'Ede',
                'Iwo',
                'Ikirun',
                'Ila Orangun',
                'Ikire',
                'Ejigbo',
                'Esa-Oke',
            ],
            'Oyo' => [
                'Ibadan',
                'Oyo',
                'Ogbomoso',
                'Iseyin',
                'Igboho',
                'Kisi',
                'Saki',
                'Eruwa',
                'Lanlate',
                'Igangan',
                'Fiditi',
                'Ilora',
            ],
            'Plateau' => [
                'Jos',
                'Bukuru',
                'Rayfield',
                'Barkin Ladi',
                'Pankshin',
                'Shendam',
                'Langtang',
                'Mangu',
                'Bassa',
                'Vom',
            ],
            'Rivers' => [
                'Port Harcourt',
                'Rumuola',
                'Rumuokwuta',
                'Rumuomasi',
                'Rumueme',
                'Elekahia',
                'Diobu',
                'Mile 1',
                'Mile 2',
                'Mile 3',
                'Trans Amadi',
                'Rumuodara',
                'Rumuigbo',
                'Rumuokoro',
                'Choba',
                'Alakahia',
                'Eliozu',
                'Woji',
                'Eneka',
                'Oginigba',
                'Isiokpo',
                'Igwuruta',
                'Aluu',
                'Ubima',
                'Eleme',
                'Onne',
                'Ogale',
                'Oyigbo',
                'Afam',
                'Bonny',
                'Finima',
                'Degema',
                'Abonnema',
                'Buguma',
                'Okrika',
                'Opobo',
                'Ahoada',
                'Omoku',
                'Emohua',
                'Bori',
            ],
            'Sokoto' => [
                'Sokoto',
                'Wamakko',
                'Tambuwal',
                'Dange-Shuni',
                'Gwadabawa',
                'Illela',
                'Goronyo',
                'Binji',
            ],
            'Taraba' => [
                'Jalingo',
                'Wukari',
                'Bali',
                'Gembu',
                'Takum',
                'Serti',
                'Zing',
                'Karim Lamido',
            ],
            'Yobe' => [
                'Damaturu',
                'Potiskum',
                'Gashua',
                'Nguru',
                'Geidam',
                'Bade',
                'Machina',
                'Fika',
            ],
            'Zamfara' => [
                'Gusau',
                'Kaura Namoda',
                'Talata Mafara',
                'Anka',
                'Bungudu',
                'Maru',
                'Tsafe',
                'Kafin Daji',
            ],
            'FCT' => [
                'Abuja',
                'Wuse',
                'Garki',
                'Maitama',
                'Asokoro',
                'Central Area',
                'Gwarinpa',
                'Life Camp',
                'Jabi',
                'Kado',
                'Kubwa',
                'Dutse',
                'Bwari',
                'Lokogoma',
                'Galadimawa',
                'Apo',
                'Gudu',
                'Durumi',
                'Lugbe',
                'Airport Road',
                'Kuje',
            ],
        ];

        foreach ($cities as $stateName => $stateCities) {
            $state = State::where('name', $stateName)->first();

            if (!$state) {
                $this->command?->warn(
                    "State [{$stateName}] was not found."
                );

                continue;
            }

            foreach ($stateCities as $cityName) {
                City::updateOrCreate(
                    [
                        'state_id' => $state->id,
                        'name' => $cityName,
                    ],
                    [
                        'is_active' => true,
                    ]
                );
            }
        }
    }
}